version: "3.8"
services:
  hapi-fhir:
    image: hapiproject/hapi:6.8.0
    container_name: hapi-fhir-server
    ports:
      - "8080:8080"
    environment:
      - HAPI_FHIR_VERSION=R4
      - HAPI_FHIR_DATASOURCE_URL=jdbc:h2:mem:testdb
      - HAPI_FHIR_DATASOURCE_USERNAME=sa
      - HAPI_FHIR_DATASOURCE_PASSWORD=
      - HAPI_FHIR_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - HAPI_FHIR_JPA_PROPERTIES_HIBERNATE_DIALECT=ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      - HAPI_FHIR_JPA_HIBERNATE_DDL_AUTO=update
      - HAPI_FHIR_PARTITIONING_ENABLED=false
      - HAPI_FHIR_PARTITIONING_DATABASE_PARTITION_MODE_ENABLED=false
      - HAPI_FHIR_PARTITIONING_PATIENT_ID_PARTITIONING_MODE=false
      - HAPI_FHIR_PARTITIONING_AUTO_CREATE_PARTITIONS=false
      - HAPI_FHIR_PARTITIONING_ALLOW_EXTERNAL_REFERENCES=false
      - HAPI_FHIR_MULTITENANCY_ENABLED=false
      - HAPI_FHIR_MULTITENANCY_TENANT_ID=default
      - HAPI_FHIR_MULTITENANCY_TENANT_ID_HEADER_NAME=X-Tenant-ID
      - HAPI_FHIR_MULTITENANCY_TENANT_ID_PARAMETER_NAME=tenant
      - HAPI_FHIR_JPA_PROPERTIES_HIBERNATE_HBM2DDL_AUTO=update
      - HAPI_FHIR_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=false
      - HAPI_FHIR_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
    restart: unless-stopped 